name: Check that documents can be built

on:
  workflow_dispatch: 
  push:
    branches: [ "main" ]

env:
  documents: |
    documents/doc1/master-1.tex
    documents/doc2/master-2.tex
  pdffiles: ""

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Show document list
      run: echo "documents=${{ env.documents }}"

    - name: Compile LaTeX document(s)
      uses: xu-cheng/latex-action@v3
      with:
        docker_image: ghcr.io/ziggymax/handy-latex-img:latest
        latexmk_shell_escape: true
        working_directory: .
        work_in_root_file_dir: true
        root_file: ${{ env.documents }}

    - name: Make list of pdf-files
      run: |
        tmp="${{ env.documents }}"
        echo "pdffiles=$(echo ${tmp/\n/ /} | sed 's/tex/pdf/g')" >> $GITHUB_ENV

    - name: Show pdf list
      run: echo "documents=${{ env.pdffiles }}"

    - name: Upload PDF file(s)
      uses: actions/upload-artifact@v3
      with:
        name: pdf-files
        path: ${{ env.pdffiles }}
